spring.application.name=BE_UNIVO
spring.datasource.url=jdbc:postgresql://localhost:10591/univo
spring.datasource.username=postgres
spring.datasource.password=1234567890

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

app.password-reset-url=http://localhost:3000/reset-password

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=support.univo@gmail.com
spring.mail.password=byjb oeoc oqnm rdha
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
